### ISSUE TITLE
[Suggestion] Remove `gorbeh_` prefix from showcase page

### ISSUE THREAD

**Issue by sinabakh** [IKAcc/Gorbeh#5]
In [showcase page](http://gorbeh.ikacc.ir/beta/), all icon's names start with `gorbeh_`. It may be better to mention the `gorbeh_` prefix for icons in page header and remove it from names, so `gorbeh_github` will become `github`.

**Comment by Javid-Izadfar** [comment]
@sinabakh I get your point and I do agree with you!

We've tested this approach at [Joqd's icon page](http://joqd.ikacc.ir/icons.html). Feedbacks however, were kind of mixed since some people prefer just "Copy and Paste". 

As you know, the page you are referring to is a beta cheatsheet. we are currently working on it's entire website (will be ready till weekend) and will consider your suggestion for sure.
